In [63]:
import pandas as pd
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.wrappers.scikit_learn import KerasClassifier
from tensorflow.keras.utils import to_categorical
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import LabelEncoder
from sklearn.pipeline import Pipeline
import pandas as pd
import numpy as np
import tensorflow
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Sequential

from tensorflow.keras.optimizers import SGD, Adam


import torch
from torch.autograd import Variable


#####################################################################
############# X_TRAIN  ##############################################
#####################################################################
x_train=[]

#file1 = open('x_train_multilabel_multiclass_dataset.txt', 'r') 
file1 = open('2nd_lev/multi-label/x_train_onelabel_multiclass.txt', 'r') 
flag=0
temp=[]
while True:

  line = file1.readline() 
  if not line: 
    break

  line = line.strip()
  if line[0]=="[" :
    
    flag=1
    line=line[1:]
    line1= line.split(" ")
    #print(line1)
    for i in range(0,len(line1)):
      if line1[i]!='':
        temp.append(float(line1[i]))


  elif line[-1]=="]" :
    flag=0
    line=line[:-2]
    line1= line.split(" ")
    #print(line1)
    for i in range(0,len(line1)):
      if line1[i]!='':
        temp.append(float(line1[i]))
    x_train.append(temp)
    temp=[]

  elif flag==1:
    
    line1= line.split(" ")
    #print(line1)
    for i in range(0,len(line1)):
      if line1[i]!='':
        temp.append(float(line1[i]))	    
	    
file1.close()

print("len(x_train) = ",len(x_train))
#####################################################################
############# X_TRAIN END ###########################################
#####################################################################


#####################################################################
############# Y_TRAIN ###############################################
#####################################################################
y_train=[]

file1 = open('2nd_lev/multi-label/y_train_onelabel_multiclass.txt', 'r')
k=0
temp=[]
while True:

  line = file1.readline()
  if not line: 
    break

  line = line.strip()
  line = line[1:-1]
  line1 = line.split(" ")
  
  temp=[]
  for i in range(0,len(line1)):
    if int(line1[i][:-1]) != 0 and int(line1[i][:-1]) != 1:
      
      temp.append(1)
    else:
      temp.append(int(float(line1[i])))
  y_train.append(temp) 
  k=k+1
   
	   
file1.close()

print("len(y_train) = ",len(y_train))
#####################################################################
############# Y_TRAIN END ###########################################
#####################################################################

'''


#####################################################################
############# X_TEST ################################################
#####################################################################
x_test=[]
file1 = open('x_test_multilabel_multiclass.txt', 'r') 
flag=0
temp=[]
while True:
  line = file1.readline() 
  if not line: 
    break
  line = line.strip()
  if line[0]=="[" :   
    flag=1
    line=line[1:]
    line1= line.split(" ")
    #print(line1)
    for i in range(0,len(line1)):
      if line1[i]!='':
        temp.append(float(line1[i]))
  elif line[-1]=="]" :
    flag=0
    line=line[:-2]
    line1= line.split(" ")
    #print(line1)
    for i in range(0,len(line1)):
      if line1[i]!='':
        temp.append(float(line1[i]))
    x_test.append(temp)
    temp=[]

  elif flag==1:
    
    line1= line.split(" ")
    #print(line1)
    for i in range(0,len(line1)):
      if line1[i]!='':
        temp.append(float(line1[i]))	    
	    
file1.close()
print("len(x_test) = ",len(x_test))
#####################################################################
############# X_TEST END ###########################################
#####################################################################



#####################################################################
############# Y_TEST ################################################
#####################################################################
y_test=[]

file1 = open('y_test_multilabel_multiclass.txt', 'r') 
k=0
temp=[]
while True:

  line = file1.readline()
  if not line: 
    break

  line = line.strip()
  line = line[1:-1]
  line1 = line.split(" ")
  
  temp=[]
  for i in range(0,len(line1)):
    if int(line1[i][:-1]) != 0 and int(line1[i][:-1]) != 1:
      
      temp.append(1)
    else:
      temp.append(int(float(line1[i])))
  y_test.append(temp) 
  k=k+1
   
	   
file1.close()

print("len(y_test) = ",len(y_test))
#####################################################################
############# Y_TEST END ###########################################
#####################################################################

x_train=np.array(x_train)
y_train=np.array(y_train)
x_test=np.array(x_test, dtype=np.float32 )
y_test=np.array(y_test, dtype=np.float32)


sikinti=0
for i in range(0,len(y_train)):
  for j in range(0, 4):
    if y_train[i][j] == 0.0:
      y_train[i][j] = 0

    elif y_train[i][j] ==1.0:
      y_train[i][j] = 1
      
 
print("sikinti = ", sikinti)


x_train = torch.from_numpy(x_train)
y_train = torch.from_numpy(y_train)
x_test = torch.from_numpy(x_test)
y_test = torch.from_numpy(y_test)
'''


len(x_train) =  2670
len(y_train) =  2670


'\n\n\n#####################################################################\n############# X_TEST ################################################\n#####################################################################\nx_test=[]\nfile1 = open(\'x_test_multilabel_multiclass.txt\', \'r\') \nflag=0\ntemp=[]\nwhile True:\n  line = file1.readline() \n  if not line: \n    break\n  line = line.strip()\n  if line[0]=="[" :   \n    flag=1\n    line=line[1:]\n    line1= line.split(" ")\n    #print(line1)\n    for i in range(0,len(line1)):\n      if line1[i]!=\'\':\n        temp.append(float(line1[i]))\n  elif line[-1]=="]" :\n    flag=0\n    line=line[:-2]\n    line1= line.split(" ")\n    #print(line1)\n    for i in range(0,len(line1)):\n      if line1[i]!=\'\':\n        temp.append(float(line1[i]))\n    x_test.append(temp)\n    temp=[]\n\n  elif flag==1:\n    \n    line1= line.split(" ")\n    #print(line1)\n    for i in range(0,len(line1)):\n      if line1[i]!=\'\':\n        temp.append(float(

In [66]:
y_train[0]

[1, 0, 0, 0]

In [19]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x_train, y_train, test_size=0.2)

In [3]:
from sklearn.utils import shuffle
x_train, y_train = shuffle(x_train, y_train)
x_test, y_test = shuffle(x_test, y_test)

In [4]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train = scaler.fit_transform( x_train )
x_test = scaler.transform( x_test )

In [20]:
x_train, y_train = torch.tensor(x_train).float(), torch.tensor(y_train)
x_test, y_test = torch.tensor(x_test).float(), torch.tensor(y_test)

In [23]:
model = torch.nn.Sequential(
    torch.nn.Linear(400, 300),
    
    torch.nn.ReLU(),
    torch.nn.Linear(300, 200),
    torch.nn.ReLU(),
    torch.nn.Linear(200, 100),
    torch.nn.ReLU(),
    torch.nn.Linear(100, 4),
    #torch.nn.ReLU(),
    #torch.nn.Linear(50, 4),
    torch.nn.Softmax()
    #torch.nn.Sigmoid()

)
loss_function = torch.nn.BCELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=5e-4, momentum=0.9)
num_epoch = 250
for epoch in range(num_epoch):
    input = Variable(x_train)
    target = Variable(y_train)
    input= torch.reshape(input, (input.shape[0], input.shape[1]))
    # forward
    out = model(input.float())
    loss = loss_function(out, target.float())

    # backward
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    # show
    #print('Epoch[{}/{}], loss: {:.6f}'
    #     .format(epoch + 1, num_epoch, loss.data.item()))

In [24]:
y_pred = model(x_test)
num_of_annots, num_of_classes = y_pred.shape
y_pred_altered = np.zeros((num_of_annots, num_of_classes))

In [25]:
y_pred

tensor([[0.2324, 0.2422, 0.2756, 0.2498],
        [0.2330, 0.2454, 0.2696, 0.2520],
        [0.2181, 0.2460, 0.2994, 0.2366],
        ...,
        [0.2419, 0.2425, 0.2602, 0.2554],
        [0.2384, 0.2430, 0.2643, 0.2544],
        [0.2420, 0.2440, 0.2562, 0.2578]], grad_fn=<SoftmaxBackward>)

In [26]:
#returns the true labels per given class
def true_labels_for_class(term):
    true_labels = list()    
    for x in y_test:
        true_labels.append(int(x[term]))
        
    return true_labels 


#returns initial prediction scores per given class
def init_pred_per_class(term):
    terms = list()    
    for x in y_pred:
        terms.append(x[term])
        
    return terms



def alter_preds(optimal_threshold, term):    
    for i in range(0, num_of_annots):
        if y_pred[i][term] > optimal_threshold:
            y_pred_altered[i][term] = 1
        else:
            y_pred_altered[i][term] = 0    
    #print(y_pred)

In [27]:
#calculates f1 score for the given class with the given threshold val
from sklearn.metrics import f1_score
def score_per_class(term, threshold, num_of_annots, true_labels):     

    preds = init_pred_per_class(term)
    
    for i in range(0, num_of_annots):
        if preds[i] > threshold:
            preds[i] = 1
        else:
            preds[i] = 0   
            
    score = f1_score(true_labels, preds, average="binary") 
    m_score = matthews_corrcoef(true_labels, preds)
    
    #print("calc f1 score:", score, "m_score:", m_score ,"on threshold:", threshold)
   

    
    return score, m_score, preds  

In [71]:
#to find the threshold values for the given class:term using f1-score
from sklearn.metrics import matthews_corrcoef
from sklearn.metrics import confusion_matrix

def treshold_per_class_f1_score(term, num_of_annots):   
    
    threshold = 0.1
    max_f1_score = -1
    optimal_threshold = -1
    max_matthews_corrcoef = -1
    true_labels = true_labels_for_class(term)    
    preds_opt = np.array(num_of_annots) 
    
    while(threshold < 1):
        
        score, matthews_corrcoef, preds = score_per_class(term, threshold, num_of_annots, true_labels)        

            
        
        if score > max_f1_score:            
            #print("calc f1 score:", score , "prev score: ", max_f1_score ,"prev threshold:", optimal_threshold)    
            max_matthews_corrcoef = matthews_corrcoef
            max_f1_score = score
            optimal_threshold = threshold   
            preds_opt = preds
            #print("new threshold:" , optimal_threshold)
            
        threshold += 0.01
        
         
        
        
        
    print("the optimal threshold is", optimal_threshold, "for term", term, " with f1-score: ", max_f1_score, " and matthews_corrcoef", max_matthews_corrcoef)
    print("confusion matrix:")
    print(confusion_matrix(true_labels, preds_opt))
    #print("preds",preds_opt)
    #print("true label",true_labels)

    
    #after finding the threshold values per class, alter the predictions 
    alter_preds(optimal_threshold, term)
    
    return optimal_threshold

In [72]:
#to find the threshold values for the given class:term using matthews_corrcoef
from sklearn.metrics import matthews_corrcoef
from sklearn.metrics import confusion_matrix

def treshold_per_class_matth(term, num_of_annots):   
    
    threshold = 0.1
    max_f1_score = -1
    optimal_threshold = -1
    max_matthews_corrcoef = -1
    true_labels = true_labels_for_class(term)    
    preds_opt = np.array(num_of_annots) 
    
    while(threshold < 1):
        
        score, matthews_corrcoef, preds = score_per_class(term, threshold, num_of_annots, true_labels)        
        #print("calc f1 score:", score ,"on threshold:", threshold)       

        if matthews_corrcoef > max_matthews_corrcoef:
            #print("matthews_corrcoef", matthews_corrcoef)
            max_matthews_corrcoef = matthews_corrcoef
            max_f1_score = score
            optimal_threshold = threshold
            preds_opt = preds
        threshold += 0.01
        
    print("the optimal threshold is", optimal_threshold, "for term", term, " with f1-score: ", max_f1_score, " and matthews_corrcoef", max_matthews_corrcoef)
    print("confusion matrix:")
    print(confusion_matrix(true_labels, preds_opt))
    #print("preds",preds_opt)
    #print("true label",true_labels)

    
    #after finding the threshold values per class, alter the predictions 
    alter_preds(optimal_threshold, term)
    
    return optimal_threshold        

In [79]:
#to find the threshold values for all classes
def all_thresholds(): 
    for i in range(0, num_of_classes):
        print("F1 SCORES")
        treshold_per_class_f1_score(i, num_of_annots)
        print()
        print("MATTHEWS CORRCOEF ")
        treshold_per_class_matth(i, num_of_annots)
        
all_thresholds()        

F1 SCORES
the optimal threshold is 0.21000000000000008 for term 0  with f1-score:  0.3155339805825243  and matthews_corrcoef 0.06511352617790299
confusion matrix:
[[188 534]
 [ 30 130]]

MATTHEWS CORRCOEF 
the optimal threshold is 0.21000000000000008 for term 0  with f1-score:  0.3155339805825243  and matthews_corrcoef 0.06511352617790299
confusion matrix:
[[188 534]
 [ 30 130]]
F1 SCORES
the optimal threshold is 0.22000000000000008 for term 1  with f1-score:  0.3675310033821872  and matthews_corrcoef 0.11338189647311747
confusion matrix:
[[158 540]
 [ 21 163]]

MATTHEWS CORRCOEF 
the optimal threshold is 0.22000000000000008 for term 1  with f1-score:  0.3675310033821872  and matthews_corrcoef 0.11338189647311747
confusion matrix:
[[158 540]
 [ 21 163]]
F1 SCORES
the optimal threshold is 0.19000000000000006 for term 2  with f1-score:  0.4827586206896552  and matthews_corrcoef 0.03251280443811776
confusion matrix:
[[  2 600]
 [  0 280]]

MATTHEWS CORRCOEF 
the optimal threshold is 0.310

In [80]:
y_test = y_test.detach().numpy()
y_pred = y_pred.detach().numpy()

AttributeError: 'numpy.ndarray' object has no attribute 'detach'

In [ ]:
y_pred_altered

In [65]:
y_test = y_test.detach().numpy()

In [66]:
f1_score(y_test, y_pred_altered, average="micro")

0.8621700879765396

In [67]:
f1_score(y_test, y_pred_altered, average="macro")

0.8560038567011725